### ISSUE TITLE
Pin 25 is not possible to switch to INPUT 

### ISSUE THREAD

**Issue by MiroslavBurda** [RoboticsBrno/RB3201-RBControl-library#15]
Piezzo hold pin 25 as OUTPUT permanently.

**Comment by bsaid** [comment]
What is exactly the problem? I think that the pin 25 should be held as output for proper work of piezo. Do you mean that ENC7 is not accessible due to the impossibility of piezo deactivation?

**Comment by cednik** [comment]
Yes, ENC7 is probably problem too (not tested). @MiroslavBurda just want to use the pin as general input.
But you can not set the pin as input (using Arduino framework pinMode), because it is connected to the PWM peripheral. (Observation, I haven't read the doc yet.)
