### ISSUE TITLE
TravisCI and library tests

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/RB3201-RBControl-library#22]
It would be nice to have some small tests for the compilation of the library in CI.
Then we can check if we didn't break compilation by ours commits.

Something as in [ALKS-library repository](https://github.com/RoboticsBrno/ArduinoLearningKitStarter-library/blob/master/.travis.yml).

**Comment by Tasssadar** [comment]
This is done already, right? https://travis-ci.org/RoboticsBrno/RB3201-RBControl-library

**Comment by JarekParal** [comment]
Yes, you are correct. Sorry for this issue.
