### ISSUE TITLE
Motor ids on board and in code do not match.

### ISSUE THREAD

**Issue by Tasssadar** [RoboticsBrno/RB3201-RBControl-library#3]
Is there some simple way of how to change the `id` and `index` in all methods for range `1 - 8`.

On the board, we have indexes of motors and encoders from 1 to 8.
![rbcontrol-motorsandencodersindexes](https://user-images.githubusercontent.com/6726556/50716428-de6cab00-1081-11e9-8414-7fedfcdb6fac.JPG)

Could we rewrite the indexes to the `enum class`? 
Is would be better to type and range control but it is probably a little bit more complex for beginners.
@Tasssadar @yaqwsx @cednik @JarekParal

**Comment by Tasssadar** [comment]
I think we can create an enum for these. The user projects are likely gonna be using their own redefines anyway, like in demo01: https://github.com/RoboticsBrno/mickoflus-demo01/blob/master/src/motors.hpp

```cpp
enum MotorId : uint8_t {
    MOTOR1,
    MOTOR2,
    MOTOR3,
    MOTOR4,
    MOTOR5,
    MOTOR6,
    MOTOR7,
    MOTOR8,

    MOTOR_MAX,
};
```
?

**Comment by JarekParal** [comment]
And what about using `enum class`:

```cpp
enum class MotorId : uint8_t {
    M1,
    M2,
    M3,
    M4,
    M5,
    M6,
    M7,
    M8,

    MOTOR_MAX,
};
```

That is typed stronger and add the information `MotorId` to code.

**Comment by JarekParal** [comment]
Will be then possible simply make something like [that](https://github.com/RoboticsBrno/mickoflus-demo01/blob/master/src/motors.hpp#L11)?

**Comment by Tasssadar** [comment]
No, it won't. See #6 and https://github.com/RoboticsBrno/mickoflus-demo01/commit/229c08d552fad831dec6c421edd9339ff07b6b8a#diff-e7f3cc39f26bb6fad47efd44155fdaa5R9
