### ISSUE TITLE
Transfer documentation from Tasemnice.eu to GitHub pages

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/RB3201-RBControl-library#8]
Transfer documentation from [Tasemnice.eu](https://technika.tasemnice.eu/docs/rbcontrol/) to GitHub pages: github.io/RoboticsBrno/RB3201-RBControl-library

Add to TravisCI script automatic deploy of the documentation to GitHub Pages.

**Comment by JarekParal** [comment]
Add TravisCI deploy to gh-pages by this commit 93a256ee29a1904fdc96471210208f73a0a886fa:
- just on master
- deploy every time when anybody makes a commit
- GH-pages: https://roboticsbrno.github.io/RB3201-RBControl-library/

**Comment by JarekParal** [comment]
Is there some problem with README.md file in the gh-pages version.

## Tasemnice.eu:
![image](https://user-images.githubusercontent.com/6726556/60755086-fac6b180-9fea-11e9-9b64-7e2179410ee5.png)

## https://roboticsbrno.github.io/RB3201-RBControl-library/
![image](https://user-images.githubusercontent.com/6726556/60755110-2fd30400-9feb-11e9-938b-160dfaea4c31.png)

@Tasssadar Could you please check it? Probably we used different Doxygen config.

**Comment by Tasssadar** [comment]
Fixed by newer travis environment.
